---
title: "Supplemental_Figs"
Date: "`r Sys.Date()`"
format: 
  gfm:
    df-print: kable
editor: visual
---

## Fig S8-S15

```{r load libraries}
library(tidyverse)
library(ggplot2)
library(cowplot)
library(VennDiagram)
library(patchwork)
```

```{r load in files}
# For figS8
aRMS_SS_up_polyAunbiased_polyAbiased_riboDbiased <- read_rds("../../output_data/aRMS_SS/aRMS_SS_up_polyAunbiased_polyAbiased_riboDbiased.rds")  # venn diagram
WT_NB_up_polyAunbiased_polyAbiased_riboDbiased <- read_rds("../../output_data/NB_WT/WT_NB_up_polyAunbiased_polyAbiased_riboDbiased.rds") # venn diagram
ALL_AML_up_polyAunbiased_polyAbiased_riboDbiased <- read_rds("../../output_data/ALL_AML/ALL_AML_up_polyAunbiased_polyAbiased_riboDbiased.rds") # venn diagram

# for figS9
aRMS_SS_up_riboDunbiased_polyAbiased_riboDbiased <- read_rds("../../output_data/aRMS_SS/aRMS_SS_up_riboDunbiased_polyAbiased_riboDbiased.rds")  # venn diagram
WT_NB_up_riboDunbiased_polyAbiased_riboDbiased <- read_rds("../../output_data/NB_WT/WT_NB_up_riboDunbiased_polyAbiased_riboDbiased.rds") # venn diagram
ALL_AML_up_riboDunbiased_polyAbiased_riboDbiased <- read_rds("../../output_data/ALL_AML/ALL_AML_up_riboDunbiased_polyAbiased_riboDbiased.rds") # venn diagram

# for figS10
aRMS_SS_up_polyAbiased <- read_rds("../../output_data/aRMS_SS/aRMS_SS_up_polyAbiased.rds") # histogram
WT_NB_up_polyAbiased <- read_rds("../../output_data/NB_WT/WT_NB_up_polyAbiased.rds") # histogram
ALL_AML_up_polyAbiased <- read_rds("../../output_data/ALL_AML/ALL_AML_up_polyAbiased.rds") # histogram

# for figS11
aRMS_SS_up_riboDbiased <- read_rds("../../output_data/aRMS_SS/aRMS_SS_up_riboDbiased.rds") # histogram
WT_NB_up_riboDbiased <- read_rds("../../output_data/NB_WT/WT_NB_up_riboDbiased.rds") # histogram
ALL_AML_up_riboDbiased <- read_rds("../../output_data/ALL_AML/ALL_AML_up_riboDbiased.rds") # histogram

# for figS12
aRMS_SS_down_polyAunbiased_polyAbiased_riboDbiased <- read_rds("../../output_data/aRMS_SS/aRMS_SS_down_polyAunbiased_polyAbiased_riboDbiased.rds")  # venn diagram
WT_NB_down_polyAunbiased_polyAbiased_riboDbiased <- read_rds("../../output_data/NB_WT/WT_NB_down_polyAunbiased_polyAbiased_riboDbiased.rds") # venn diagram
ALL_AML_down_polyAunbiased_polyAbiased_riboDbiased <- read_rds("../../output_data/ALL_AML/ALL_AML_down_polyAunbiased_polyAbiased_riboDbiased.rds") # venn diagram

# for figS13
aRMS_SS_down_riboDunbiased_polyAbiased_riboDbiased <- read_rds("../../output_data/aRMS_SS/aRMS_SS_down_riboDunbiased_polyAbiased_riboDbiased.rds")  # venn diagram
WT_NB_down_riboDunbiased_polyAbiased_riboDbiased <- read_rds("../../output_data/NB_WT/WT_NB_down_riboDunbiased_polyAbiased_riboDbiased.rds") # venn diagram
ALL_AML_down_riboDunbiased_polyAbiased_riboDbiased <- read_rds("../../output_data/ALL_AML/ALL_AML_down_riboDunbiased_polyAbiased_riboDbiased.rds") # venn diagram

# for figS14
aRMS_SS_down_polyAbiased <- read_rds("../../output_data/aRMS_SS/aRMS_SS_down_polyAbiased.rds") # histogram
WT_NB_down_polyAbiased <- read_rds("../../output_data/NB_WT/WT_NB_down_polyAbiased.rds") # histogram
ALL_AML_down_polyAbiased <- read_rds("../../output_data/ALL_AML/ALL_AML_down_polyAbiased.rds") # histogram

# for figS15
aRMS_SS_down_riboDbiased <- read_rds("../../output_data/aRMS_SS/aRMS_SS_down_riboDbiased.rds") # histogram
WT_NB_down_riboDbiased <- read_rds("../../output_data/NB_WT/WT_NB_down_riboDbiased.rds") # histogram
ALL_AML_down_riboDbiased <- read_rds("../../output_data/ALL_AML/ALL_AML_down_riboDbiased.rds") # histogram


# for figS16
down_polyAbiased_all <- read_rds("../../output_data/all_disease_comparisons/down_polyAbiased_all.rds") # venn diagram

# for figS17
down_riboDbiased_all <- read_rds("../../output_data/all_disease_comparisons/down_riboDbiased_all.rds") # venn diagram

```

### Fig S8

```{r Fig_S8}
# for fig S8
# aRMS v SS
aRMS_SS_up_polyAunbiased_polyAbiased_riboDbiased_VD <- venn.diagram(
  x = aRMS_SS_up_polyAunbiased_polyAbiased_riboDbiased,
  category.names = c(
    "PolyA unbiased",
    "PolyA biased",
    "RiboD biased"
    ),
  filename = NULL, # Save as a PNG file
  output = TRUE,
  print.mode = c("raw", "percent"),
  # Customize appearance (optional)
  fill = c("#BB5566", "#0072B2", "#E69F00"),
#  cat.col = c("#BB5566", "#0072B2", "#E69F00"),
  cex = 0.9, # Font size for counts
  cat.cex = 0.9, # Font size for category names
  cat.dist = c(0.04, 0.04, 0.04),
  # height = 1000,
  # width = 1000,
  cat.default.pos = "outer",
  cat.pos = c(-14, 14, 175), 
  main = "Upregulated genes in\nSS relative to aRMS",
  main.cex = 1.1, # Font size for main title
  main.pos = c(0.5, 1.2), 
  disable.logging = TRUE,
  sigdigs = 3, 
  cat.fontfamily = "sans",
  main.fontfamily = "sans",
  fontfamily = "sans"
)

# NB v WT
WT_NB_up_polyAunbiased_polyAbiased_riboDbiased_VD <- venn.diagram(
  x = WT_NB_up_polyAunbiased_polyAbiased_riboDbiased,
  category.names = c(
    "PolyA unbiased",
    "PolyA biased",
    "RiboD biased"
    ),
  filename = NULL, # Save as a PNG file
  output = TRUE,
  print.mode = c("raw", "percent"),
  # Customize appearance (optional)
  fill = c("#BB5566", "#0072B2", "#E69F00"),
#  cat.col = c("#BB5566", "#0072B2", "#E69F00"),
  cex = 0.9, # Font size for counts
  cat.cex = 0.9, # Font size for category names
  cat.dist = c(0.04, 0.04, 0.04),
  # height = 1000,
  # width = 1000,
  cat.default.pos = "outer",
  cat.pos = c(-14, 14, 175), 
  main = "Upregulated genes in\nWT relative to NB",
  main.cex = 1.1, # Font size for main title
  main.pos = c(0.5, 1.2), 
  disable.logging = TRUE,
  sigdigs = 3, 
  cat.fontfamily = "sans",
  main.fontfamily = "sans",
  fontfamily = "sans"
)


# NB v WT
ALL_AML_up_polyAunbiased_polyAbiased_riboDbiased_VD <- venn.diagram(
  x = ALL_AML_up_polyAunbiased_polyAbiased_riboDbiased,
  category.names = c(
    "PolyA unbiased",
    "PolyA biased",
    "RiboD biased"
    ),
  filename = NULL, # Save as a PNG file
  output = TRUE,
  print.mode = c("raw", "percent"),
  # Customize appearance (optional)
  fill = c("#BB5566", "#0072B2", "#E69F00"),
#  cat.col = c("#BB5566", "#0072B2", "#E69F00"),
  cex = 0.9, # Font size for counts
  cat.cex = 0.9, # Font size for category names
  cat.dist = c(0.04, 0.04, 0.04),
  # height = 1000,
  # width = 1000,
  cat.default.pos = "outer",
  cat.pos = c(-14, 14, 175), 
  main = "Upregulated genes in\nAML relative to ALL",
  main.cex = 1.1, # Font size for main title
  main.pos = c(0.5, 1.2), 
  disable.logging = TRUE,
  sigdigs = 3, 
  cat.fontfamily = "sans",
  main.fontfamily = "sans",
  fontfamily = "sans"
)

Fig_S8 <- plot_grid(
  aRMS_SS_up_polyAunbiased_polyAbiased_riboDbiased_VD,
  WT_NB_up_polyAunbiased_polyAbiased_riboDbiased_VD,
  ALL_AML_up_polyAunbiased_polyAbiased_riboDbiased_VD,
  ncol = 3,
  label_size = 15)

ggsave("../../Figures/Fig_S8.png", Fig_S8, width = 10, height = 3, dpi = 300)
```

### Fig S9

```{r Fig_S9}
# for fig S9
# aRMS v SS
aRMS_SS_up_riboDunbiased_polyAbiased_riboDbiased_VD <- venn.diagram(
  x = aRMS_SS_up_riboDunbiased_polyAbiased_riboDbiased,
  category.names = c(
    "RiboD unbiased",
    "PolyA biased",
    "RiboD biased"
    ),
  filename = NULL, # Save as a PNG file
  output = TRUE,
  print.mode = c("raw", "percent"),
  # Customize appearance (optional)
  fill = c("#BB5566", "#0072B2", "#E69F00"),
#  cat.col = c("#BB5566", "#0072B2", "#E69F00"),
  cex = 0.9, # Font size for counts
  cat.cex = 0.9, # Font size for category names
  cat.dist = c(0.04, 0.04, 0.04),
  # height = 1000,
  # width = 1000,
  cat.default.pos = "outer",
  cat.pos = c(-14, 14, 175), 
  main = "Upregulated genes in\nSS relative to aRMS",
  main.cex = 1.1, # Font size for main title
  main.pos = c(0.5, 1.2), 
  disable.logging = TRUE,
  sigdigs = 3, 
  cat.fontfamily = "sans",
  main.fontfamily = "sans",
  fontfamily = "sans"
)

# NB v WT
WT_NB_up_riboDunbiased_polyAbiased_riboDbiased_VD <- venn.diagram(
  x = WT_NB_up_riboDunbiased_polyAbiased_riboDbiased,
  category.names = c(
    "RiboD unbiased",
    "PolyA biased",
    "RiboD biased"
    ),
  filename = NULL, # Save as a PNG file
  output = TRUE,
  print.mode = c("raw", "percent"),
  # Customize appearance (optional)
  fill = c("#BB5566", "#0072B2", "#E69F00"),
#  cat.col = c("#BB5566", "#0072B2", "#E69F00"),
  cex = 0.9, # Font size for counts
  cat.cex = 0.9, # Font size for category names
  cat.dist = c(0.04, 0.04, 0.04),
  # height = 1000,
  # width = 1000,
  cat.default.pos = "outer",
  cat.pos = c(-14, 14, 175), 
  main = "Upregulated genes in\nWT relative to NB",
  main.cex = 1.1, # Font size for main title
  main.pos = c(0.5, 1.2), 
  disable.logging = TRUE,
  sigdigs = 3, 
  cat.fontfamily = "sans",
  main.fontfamily = "sans",
  fontfamily = "sans"
)


# NB v WT
ALL_AML_up_riboDunbiased_polyAbiased_riboDbiased_VD <- venn.diagram(
  x = ALL_AML_up_riboDunbiased_polyAbiased_riboDbiased,
  category.names = c(
    "RiboD unbiased",
    "PolyA biased",
    "RiboD biased"
    ),
  filename = NULL, # Save as a PNG file
  output = TRUE,
  print.mode = c("raw", "percent"),
  # Customize appearance (optional)
  fill = c("#BB5566", "#0072B2", "#E69F00"),
#  cat.col = c("#BB5566", "#0072B2", "#E69F00"),
  cex = 0.9, # Font size for counts
  cat.cex = 0.9, # Font size for category names
  cat.dist = c(0.04, 0.04, 0.04),
  # height = 1000,
  # width = 1000,
  cat.default.pos = "outer",
  cat.pos = c(-14, 14, 175), 
  main = "Upregulated genes in\nAML relative to ALL",
  main.cex = 1.1, # Font size for main title
  main.pos = c(0.5, 1.2), 
  disable.logging = TRUE,
  sigdigs = 3, 
  cat.fontfamily = "sans",
  main.fontfamily = "sans",
  fontfamily = "sans"
)

Fig_S9 <- plot_grid(
  aRMS_SS_up_riboDunbiased_polyAbiased_riboDbiased_VD,
  WT_NB_up_riboDunbiased_polyAbiased_riboDbiased_VD,
  ALL_AML_up_riboDunbiased_polyAbiased_riboDbiased_VD,
  ncol = 3,
  label_size = 15)

ggsave("../../Figures/Fig_S9.png", Fig_S9, width = 10, height = 3, dpi = 300)
```

### Fig S10

```{r medians for Fig_S10}
# aRMS v SS
aRMS_SS_up_polyAbiased_median <- aRMS_SS_up_polyAbiased %>%
  summarise(
    median_value = median(log2FoldChange.x),
  )
aRMS_SS_up_polyAbiased_median

# NB v WT
WT_NB_up_polyAbiased_median <- WT_NB_up_polyAbiased %>%
  summarise(
    median_value = median(log2FoldChange.x),
  )
WT_NB_up_polyAbiased_median

# AML v ALL
ALL_AML_up_polyAbiased_median <- ALL_AML_up_polyAbiased %>%
  summarise(
    median_value = median(log2FoldChange.x),
  )
ALL_AML_up_polyAbiased_median
```

```{r Fig_S10}
# aRMS v SS
aRMS_SS_up_polyAbiased_hist <- ggplot(aRMS_SS_up_polyAbiased, aes(x = log2FoldChange.x)) +
  geom_histogram(
    bins = 30, # 30 is default
    fill = "#0072B2",
    color = "#0072B2",
    alpha = 0.7
    ) +
#  scale_y_continuous(breaks = c(200, 400, 600, 800), limits = c(0,1000)) +
#  scale_x_continuous(breaks = c(2, 4, 6, 8, 10, 12, 14, 16)) +
  labs(
    title = "Upregulated in\naRMS v SS",
#    subtitle = "polyA biased, Median LFC = 1.32",
    y = "Number of genes unique to PolyA biased",
    x = "log2 Fold Change"
) +
  theme(plot.title = element_text(hjust = 0.5, size = 12),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12)
        ) +
  geom_vline(aes(xintercept = aRMS_SS_up_polyAbiased_median$median_value), color = "#004166", linetype = "dashed", linewidth = 0.5) +
  annotate("text", x=3.7, y=580, label= "Median = 1.32")

# NB v WT
WT_NB_up_polyAbiased_hist <- ggplot(WT_NB_up_polyAbiased, aes(x = log2FoldChange.x)) +
  geom_histogram(
    bins = 30, # 30 is default
    fill = "#0072B2",
    color = "#0072B2",
    alpha = 0.7
    ) +
#  scale_y_continuous(breaks = c(200, 400, 600, 800), limits = c(0,1000)) +
#  scale_x_continuous(breaks = c(2, 4, 6, 8, 10, 12, 14, 16)) +
  labs(
    title = "Upregulated in\nNB v WT",
#    subtitle = "polyA biased, Median LFC = 1.32",
    y = "Number of genes unique to PolyA biased",
    x = "log2 Fold Change"
) +
  theme(plot.title = element_text(hjust = 0.5, size = 12),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12)
        ) +
  geom_vline(aes(xintercept = WT_NB_up_polyAbiased_median$median_value), color = "#004166", linetype = "dashed", linewidth = 0.5) +
  annotate("text", x=7, y=1080, label= "Median = 1.43")

# AML v ALL
ALL_AML_up_polyAbiased_hist <- ggplot(ALL_AML_up_polyAbiased, aes(x = log2FoldChange.x)) +
  geom_histogram(
    bins = 30, # 30 is default
    fill = "#0072B2",
    color = "#0072B2",
    alpha = 0.7
    ) +
#  scale_y_continuous(breaks = c(200, 400, 600, 800), limits = c(0,1000)) +
#  scale_x_continuous(breaks = c(2, 4, 6, 8, 10, 12, 14, 16)) +
  labs(
    title = "Upregulated in\nALL v AML",
#    subtitle = "polyA biased, Median LFC = 1.32",
    y = "Number of genes unique to PolyA biased",
    x = "log2 Fold Change"
) +
  theme(plot.title = element_text(hjust = 0.5, size = 12),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12)
        ) +
  geom_vline(aes(xintercept = ALL_AML_up_polyAbiased_median$median_value), color = "#004166", linetype = "dashed", linewidth = 0.5) +
  annotate("text", x=3.7, y=580, label= "Median = 1.34")

Fig_S10 <- wrap_plots(
  aRMS_SS_up_polyAbiased_hist,
  WT_NB_up_polyAbiased_hist,
  ALL_AML_up_polyAbiased_hist,
  ncol = 3) +
  plot_layout(guides = "collect", axis_titles = "collect", axes = "collect") &
  theme(
    plot.margin = margin(t = 2, b = 2, l = 4, r = 4),
    plot.title = element_text(hjust = 0.35, face = "bold", size = 14),
    legend.title = element_text(size = 12)
  )
Fig_S10

ggsave("../../Figures/Fig_S10.png", Fig_S10, width = 10, height = 3.4, dpi = 300)
```

### Fig S11

```{r medians for FigS11}
# aRMS v SS
aRMS_SS_up_riboDbiased_median <- aRMS_SS_up_riboDbiased %>%
  summarise(
    median_value = median(log2FoldChange.x),
  )
aRMS_SS_up_riboDbiased_median

# NB v WT
WT_NB_up_riboDbiased_median <- WT_NB_up_riboDbiased %>%
  summarise(
    median_value = median(log2FoldChange.x),
  )
WT_NB_up_riboDbiased_median

# AML v ALL
ALL_AML_up_riboDbiased_median <- ALL_AML_up_riboDbiased %>%
  summarise(
    median_value = median(log2FoldChange.x),
  )
ALL_AML_up_riboDbiased_median
```

```{r Fig_S11}
# aRMS v SS
aRMS_SS_up_riboDbiased_hist <- ggplot(aRMS_SS_up_riboDbiased, aes(x = log2FoldChange.x)) +
  geom_histogram(
    bins = 30, # 30 is default
    fill = "#E69F00",
    color = "#E69F00",
    alpha = 0.7
    ) +
#  scale_y_continuous(breaks = c(200, 400, 600, 800), limits = c(0,1000)) +
#  scale_x_continuous(breaks = c(2, 4, 6, 8, 10, 12, 14, 16)) +
  labs(
    title = "Upregulated in\naRMS v SS",
    y = "Number of genes unique to RiboD biased",
    x = "log2 Fold Change"
) +
  theme(plot.title = element_text(hjust = 0.5, size = 12),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12)
        ) +
  geom_vline(aes(xintercept = aRMS_SS_up_riboDbiased_median$median_value), color = "#9a6a00", linetype = "dashed", linewidth = 0.5) +
  annotate("text", x=8, y=750, label= "Median = 2.76")


# NB v WT
WT_NB_up_riboDbiased_hist <- ggplot(WT_NB_up_riboDbiased, aes(x = log2FoldChange.x)) +
  geom_histogram(
    bins = 30, # 30 is default
    fill = "#E69F00",
    color = "#E69F00",
    alpha = 0.7
    ) +
#  scale_y_continuous(breaks = c(200, 400, 600, 800), limits = c(0,1000)) +
#  scale_x_continuous(breaks = c(2, 4, 6, 8, 10, 12, 14, 16)) +
  labs(
    title = "Upregulated in\nNB v WT",
    y = "Number of genes unique to RiboD biased",
    x = "log2 Fold Change"
) +
  theme(plot.title = element_text(hjust = 0.5, size = 12),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12)
        ) +
  geom_vline(aes(xintercept = WT_NB_up_riboDbiased_median$median_value), color = "#9a6a00", linetype = "dashed", linewidth = 0.5) +
  annotate("text", x=6, y=700, label= "Median = 2.60")

# AML v ALL
ALL_AML_up_riboDbiased_hist <- ggplot(ALL_AML_up_riboDbiased, aes(x = log2FoldChange.x)) +
  geom_histogram(
    bins = 30, # 30 is default
    fill = "#E69F00",
    color = "#E69F00",
    alpha = 0.7
    ) +
#  scale_y_continuous(breaks = c(200, 400, 600, 800), limits = c(0,1000)) +
#  scale_x_continuous(breaks = c(2, 4, 6, 8, 10, 12, 14, 16)) +
  labs(
    title = "Upregulated in\nAML v ALL",
    y = "Number of genes unique to RiboD biased",
    x = "log2 Fold Change"
) +
  theme(plot.title = element_text(hjust = 0.5, size = 12),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12)
        ) +
  geom_vline(aes(xintercept = ALL_AML_up_riboDbiased_median$median_value), color = "#9a6a00", linetype = "dashed", linewidth = 0.5) +
  annotate("text", x=5, y=500, label= "Median = 1.75")

Fig_S11 <- wrap_plots(
  aRMS_SS_up_riboDbiased_hist,
  WT_NB_up_riboDbiased_hist,
  ALL_AML_up_riboDbiased_hist,
  ncol = 3) +
  plot_layout(guides = "collect", axis_titles = "collect", axes = "collect") &
  theme(
    plot.margin = margin(t = 2, b = 2, l = 4, r = 4),
    plot.title = element_text(hjust = 0.35, face = "bold", size = 14),
    legend.title = element_text(size = 12)
  )
Fig_S11

ggsave("../../Figures/Fig_S11.png", Fig_S11, width = 10, height = 3.4, dpi = 300)
```

### Fig S12

```{r Fig_S12}
# for fig S12 - downregulated genes
# aRMS v SS
aRMS_SS_down_polyAunbiased_polyAbiased_riboDbiased_VD <- venn.diagram(
  x = aRMS_SS_down_polyAunbiased_polyAbiased_riboDbiased,
  category.names = c(
    "PolyA unbiased",
    "PolyA biased",
    "RiboD biased"
    ),
  filename = NULL, # Save as a PNG file
  output = TRUE,
  print.mode = c("raw", "percent"),
  # Customize appearance (optional)
  fill = c("#BB5566", "#0072B2", "#E69F00"),
#  cat.col = c("#BB5566", "#0072B2", "#E69F00"),
  cex = 0.9, # Font size for counts
  cat.cex = 0.9, # Font size for category names
  cat.dist = c(0.04, 0.04, 0.04),
  # height = 1000,
  # width = 1000,
  cat.default.pos = "outer",
  cat.pos = c(-14, 14, 175), 
  main = "Downregulated genes in\nSS relative to aRMS",
  main.cex = 1.1, # Font size for main title
  main.pos = c(0.5, 1.2), 
  disable.logging = TRUE,
  sigdigs = 3, 
  cat.fontfamily = "sans",
  main.fontfamily = "sans",
  fontfamily = "sans"
)

# NB v WT
WT_NB_down_polyAunbiased_polyAbiased_riboDbiased_VD <- venn.diagram(
  x = WT_NB_down_polyAunbiased_polyAbiased_riboDbiased,
  category.names = c(
    "PolyA unbiased",
    "PolyA biased",
    "RiboD biased"
    ),
  filename = NULL, # Save as a PNG file
  output = TRUE,
  print.mode = c("raw", "percent"),
  # Customize appearance (optional)
  fill = c("#BB5566", "#0072B2", "#E69F00"),
#  cat.col = c("#BB5566", "#0072B2", "#E69F00"),
  cex = 0.9, # Font size for counts
  cat.cex = 0.9, # Font size for category names
  cat.dist = c(0.04, 0.04, 0.04),
  # height = 1000,
  # width = 1000,
  cat.default.pos = "outer",
  cat.pos = c(-14, 14, 175), 
  main = "Downregulated genes in\nWT relative to NB",
  main.cex = 1.1, # Font size for main title
  main.pos = c(0.5, 1.2), 
  disable.logging = TRUE,
  sigdigs = 3, 
  cat.fontfamily = "sans",
  main.fontfamily = "sans",
  fontfamily = "sans"
)


# NB v WT
ALL_AML_down_polyAunbiased_polyAbiased_riboDbiased_VD <- venn.diagram(
  x = ALL_AML_down_polyAunbiased_polyAbiased_riboDbiased,
  category.names = c(
    "PolyA unbiased",
    "PolyA biased",
    "RiboD biased"
    ),
  filename = NULL, # Save as a PNG file
  output = TRUE,
  print.mode = c("raw", "percent"),
  # Customize appearance (optional)
  fill = c("#BB5566", "#0072B2", "#E69F00"),
#  cat.col = c("#BB5566", "#0072B2", "#E69F00"),
  cex = 0.9, # Font size for counts
  cat.cex = 0.9, # Font size for category names
  cat.dist = c(0.04, 0.04, 0.04),
  # height = 1000,
  # width = 1000,
  cat.default.pos = "outer",
  cat.pos = c(-14, 14, 175), 
  main = "Downregulated genes in\nAML relative to ALL",
  main.cex = 1.1, # Font size for main title
  main.pos = c(0.5, 1.2), 
  disable.logging = TRUE,
  sigdigs = 3, 
  cat.fontfamily = "sans",
  main.fontfamily = "sans",
  fontfamily = "sans"
)

Fig_S12 <- plot_grid(
  aRMS_SS_down_polyAunbiased_polyAbiased_riboDbiased_VD,
  WT_NB_down_polyAunbiased_polyAbiased_riboDbiased_VD,
  ALL_AML_down_polyAunbiased_polyAbiased_riboDbiased_VD,
  ncol = 3,
  label_size = 15)

ggsave("../../Figures/Fig_S12.png", Fig_S12, width = 10, height = 3, dpi = 300)
```

### Fig S13

```{r Fig_S13}
# for fig S13
# aRMS v SS
aRMS_SS_down_riboDunbiased_polyAbiased_riboDbiased_VD <- venn.diagram(
  x = aRMS_SS_down_riboDunbiased_polyAbiased_riboDbiased,
  category.names = c(
    "RiboD unbiased",
    "PolyA biased",
    "RiboD biased"
    ),
  filename = NULL, # Save as a PNG file
  output = TRUE,
  print.mode = c("raw", "percent"),
  # Customize appearance (optional)
  fill = c("#BB5566", "#0072B2", "#E69F00"),
#  cat.col = c("#BB5566", "#0072B2", "#E69F00"),
  cex = 0.9, # Font size for counts
  cat.cex = 0.9, # Font size for category names
  cat.dist = c(0.04, 0.04, 0.04),
  # height = 1000,
  # width = 1000,
  cat.default.pos = "outer",
  cat.pos = c(-14, 14, 175), 
  main = "Downregulated genes in\nSS relative to aRMS",
  main.cex = 1.1, # Font size for main title
  main.pos = c(0.5, 1.2), 
  disable.logging = TRUE,
  sigdigs = 3, 
  cat.fontfamily = "sans",
  main.fontfamily = "sans",
  fontfamily = "sans"
)

# NB v WT
WT_NB_down_riboDunbiased_polyAbiased_riboDbiased_VD <- venn.diagram(
  x = WT_NB_down_riboDunbiased_polyAbiased_riboDbiased,
  category.names = c(
    "RiboD unbiased",
    "PolyA biased",
    "RiboD biased"
    ),
  filename = NULL, # Save as a PNG file
  output = TRUE,
  print.mode = c("raw", "percent"),
  # Customize appearance (optional)
  fill = c("#BB5566", "#0072B2", "#E69F00"),
#  cat.col = c("#BB5566", "#0072B2", "#E69F00"),
  cex = 0.9, # Font size for counts
  cat.cex = 0.9, # Font size for category names
  cat.dist = c(0.04, 0.04, 0.04),
  # height = 1000,
  # width = 1000,
  cat.default.pos = "outer",
  cat.pos = c(-14, 14, 175), 
  main = "Downregulated genes in\nWT relative to NB",
  main.cex = 1.1, # Font size for main title
  main.pos = c(0.5, 1.2), 
  disable.logging = TRUE,
  sigdigs = 3, 
  cat.fontfamily = "sans",
  main.fontfamily = "sans",
  fontfamily = "sans"
)


# NB v WT
ALL_AML_down_riboDunbiased_polyAbiased_riboDbiased_VD <- venn.diagram(
  x = ALL_AML_down_riboDunbiased_polyAbiased_riboDbiased,
  category.names = c(
    "RiboD unbiased",
    "PolyA biased",
    "RiboD biased"
    ),
  filename = NULL, # Save as a PNG file
  output = TRUE,
  print.mode = c("raw", "percent"),
  # Customize appearance (optional)
  fill = c("#BB5566", "#0072B2", "#E69F00"),
#  cat.col = c("#BB5566", "#0072B2", "#E69F00"),
  cex = 0.9, # Font size for counts
  cat.cex = 0.9, # Font size for category names
  cat.dist = c(0.04, 0.04, 0.04),
  # height = 1000,
  # width = 1000,
  cat.default.pos = "outer",
  cat.pos = c(-14, 14, 175), 
  main = "Downregulated genes in\nAML relative to ALL",
  main.cex = 1.1, # Font size for main title
  main.pos = c(0.5, 1.2), 
  disable.logging = TRUE,
  sigdigs = 3, 
  cat.fontfamily = "sans",
  main.fontfamily = "sans",
  fontfamily = "sans"
)

Fig_S13 <- plot_grid(
  aRMS_SS_down_riboDunbiased_polyAbiased_riboDbiased_VD,
  WT_NB_down_riboDunbiased_polyAbiased_riboDbiased_VD,
  ALL_AML_down_riboDunbiased_polyAbiased_riboDbiased_VD,
  ncol = 3,
  label_size = 15)

ggsave("../../Figures/Fig_S13.png", Fig_S13, width = 10, height = 3, dpi = 300)
```

### Fig S14

```{r medians for figS14}
# aRMS v SS
aRMS_SS_down_polyAbiased_median <- aRMS_SS_down_polyAbiased %>%
  summarise(
    median_value = median(log2FoldChange.x),
  )
aRMS_SS_down_polyAbiased_median

# NB v WT
WT_NB_down_polyAbiased_median <- WT_NB_down_polyAbiased %>%
  summarise(
    median_value = median(log2FoldChange.x),
  )
WT_NB_down_polyAbiased_median

# AML v ALL
ALL_AML_down_polyAbiased_median <- ALL_AML_down_polyAbiased %>%
  summarise(
    median_value = median(log2FoldChange.x),
  )
ALL_AML_down_polyAbiased_median
```

```{r Fig_S14}
# aRMS v SS
aRMS_SS_down_polyAbiased_hist <- ggplot(aRMS_SS_down_polyAbiased, aes(x = log2FoldChange.x)) +
  geom_histogram(
    bins = 30, # 30 is default
    fill = "#0072B2",
    color = "#0072B2",
    alpha = 0.7
    ) +
#  scale_y_continuous(breaks = c(200, 400, 600, 800), limits = c(0,1000)) +
#  scale_x_continuous(breaks = c(2, 4, 6, 8, 10, 12, 14, 16)) +
  labs(
    title = "Downregulated in\naRMS v SS",
    y = "Number of genes unique to PolyA biased",
    x = "log2 Fold Change"
) +
  theme(plot.title = element_text(hjust = 0.5, size = 12),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12)
        ) +
  geom_vline(aes(xintercept = aRMS_SS_down_polyAbiased_median$median_value), color = "#004166", linetype = "dashed", linewidth = 0.5) +
  annotate("text", x=-7, y=580, label= "Median = -2.9")

# NB v WT
WT_NB_down_polyAbiased_hist <- ggplot(WT_NB_down_polyAbiased, aes(x = log2FoldChange.x)) +
  geom_histogram(
    bins = 30, # 30 is default
    fill = "#0072B2",
    color = "#0072B2",
    alpha = 0.7
    ) +
#  scale_y_continuous(breaks = c(200, 400, 600, 800), limits = c(0,1000)) +
#  scale_x_continuous(breaks = c(2, 4, 6, 8, 10, 12, 14, 16)) +
  labs(
    title = "Downregulated in\nNB v WT",
    y = "Number of genes unique to PolyA biased",
    x = "log2 Fold Change"
) +
  theme(plot.title = element_text(hjust = 0.5, size = 12),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12)
        ) +
  geom_vline(aes(xintercept = WT_NB_down_polyAbiased_median$median_value), color = "#004166", linetype = "dashed", linewidth = 0.5) +
  annotate("text", x=-10, y=750, label= "Median = -3.1")

# AML v ALL
ALL_AML_down_polyAbiased_hist <- ggplot(ALL_AML_down_polyAbiased, aes(x = log2FoldChange.x)) +
  geom_histogram(
    bins = 30, # 30 is default
    fill = "#0072B2",
    color = "#0072B2",
    alpha = 0.7
    ) +
#  scale_y_continuous(breaks = c(200, 400, 600, 800), limits = c(0,1000)) +
#  scale_x_continuous(breaks = c(2, 4, 6, 8, 10, 12, 14, 16)) +
  labs(
    title = "Downregulated in\nALL v AML",
    y = "Number of genes unique to PolyA biased",
    x = "log2 Fold Change"
) +
  theme(plot.title = element_text(hjust = 0.5, size = 12),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12)
        ) +
  geom_vline(aes(xintercept = ALL_AML_down_polyAbiased_median$median_value), color = "#004166", linetype = "dashed", linewidth = 0.5) +
  annotate("text", x=-6.7, y=750, label= "Median = -1.62")

Fig_S14 <- wrap_plots(
  aRMS_SS_down_polyAbiased_hist,
  WT_NB_down_polyAbiased_hist,
  ALL_AML_down_polyAbiased_hist,
  ncol = 3) +
  plot_layout(guides = "collect", axis_titles = "collect") &
  theme(
    plot.margin = margin(t = 2, b = 2, l = 4, r = 4),
    plot.title = element_text(hjust = 0.35, face = "bold", size = 14),
    legend.title = element_text(size = 12)
  )
Fig_S14

ggsave("../../Figures/Fig_S14.png", Fig_S14, width = 10, height = 3.4, dpi = 300)
```

### Fig S15

```{r medians for figS15}
# aRMS v SS
aRMS_SS_down_riboDbiased_median <- aRMS_SS_down_riboDbiased %>%
  summarise(
    median_value = median(log2FoldChange.x),
  )
aRMS_SS_down_riboDbiased_median

# NB v WT
WT_NB_down_riboDbiased_median <- WT_NB_down_riboDbiased %>%
  summarise(
    median_value = median(log2FoldChange.x),
  )
WT_NB_down_riboDbiased_median

# AML v ALL
ALL_AML_down_riboDbiased_median <- ALL_AML_down_riboDbiased %>%
  summarise(
    median_value = median(log2FoldChange.x),
  )
ALL_AML_down_riboDbiased_median
```

```{r Fig_S15}
# aRMS v SS
aRMS_SS_down_riboDbiased_hist <- ggplot(aRMS_SS_down_riboDbiased, aes(x = log2FoldChange.x)) +
  geom_histogram(
    bins = 30, # 30 is default
    fill = "#E69F00",
    color = "#E69F00",
    alpha = 0.7
    ) +
#  scale_y_continuous(breaks = c(200, 400, 600, 800), limits = c(0,1000)) +
#  scale_x_continuous(breaks = c(2, 4, 6, 8, 10, 12, 14, 16)) +
  labs(
    title = "Downregulated in\naRMS v SS",
    y = "Number of genes unique to RiboD biased",
    x = "log2 Fold Change"
) +
  theme(plot.title = element_text(hjust = 0.5, size = 12),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12)
        ) +
  geom_vline(aes(xintercept = aRMS_SS_down_riboDbiased_median$median_value), color = "#9a6a00", linetype = "dashed", linewidth = 0.5) +
  annotate("text", x=-8, y=700, label= "Median = -1.36")


# NB v WT
WT_NB_down_riboDbiased_hist <- ggplot(WT_NB_down_riboDbiased, aes(x = log2FoldChange.x)) +
  geom_histogram(
    bins = 30, # 30 is default
    fill = "#E69F00",
    color = "#E69F00",
    alpha = 0.7
    ) +
#  scale_y_continuous(breaks = c(200, 400, 600, 800), limits = c(0,1000)) +
#  scale_x_continuous(breaks = c(2, 4, 6, 8, 10, 12, 14, 16)) +
  labs(
    title = "Downregulated in\nNB v WT",
    y = "Number of genes unique to RiboD biased",
    x = "log2 Fold Change"
) +
  theme(plot.title = element_text(hjust = 0.5, size = 12),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12)
        ) +
  geom_vline(aes(xintercept = WT_NB_down_riboDbiased_median$median_value), color = "#9a6a00", linetype = "dashed", linewidth = 0.5) +
  annotate("text", x=-5, y=400, label= "Median = -1.33")

# AML v ALL
ALL_AML_down_riboDbiased_hist <- ggplot(ALL_AML_down_riboDbiased, aes(x = log2FoldChange.x)) +
  geom_histogram(
    bins = 30, # 30 is default
    fill = "#E69F00",
    color = "#E69F00",
    alpha = 0.7
    ) +
#  scale_y_continuous(breaks = c(200, 400, 600, 800), limits = c(0,1000)) +
#  scale_x_continuous(breaks = c(2, 4, 6, 8, 10, 12, 14, 16)) +
  labs(
    title = "Downregulated in\nAML v ALL",
    y = "Number of genes unique to RiboD biased",
    x = "log2 Fold Change"
) +
  theme(plot.title = element_text(hjust = 0.5, size = 12),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12)
        ) +
  geom_vline(aes(xintercept = ALL_AML_down_riboDbiased_median$median_value), color = "#9a6a00", linetype = "dashed", linewidth = 0.5) +
  annotate("text", x=-5, y=400, label= "Median = -1.30")

Fig_S15 <- wrap_plots(
  aRMS_SS_down_riboDbiased_hist,
  WT_NB_down_riboDbiased_hist,
  ALL_AML_down_riboDbiased_hist,
  ncol = 3) +
  plot_layout(guides = "collect", axis_titles = "collect", axes = "collect") &
  theme(
    plot.margin = margin(t = 2, b = 2, l = 4, r = 4),
    plot.title = element_text(hjust = 0.35, face = "bold", size = 14),
    legend.title = element_text(size = 12)
  )
Fig_S15

ggsave("../../Figures/Fig_S15.png", Fig_S15, width = 10, height = 3.4, dpi = 300)
```

### Fig S16

```{r Fig_S16}
Fig_S16 <- venn.diagram(
  x = down_polyAbiased_all,
  category.names = c(
    "SS to aRMS",
    "WT to NB",
    "AML to ALL"
    ),
  filename = NULL, # Save as a rds file
  output = TRUE,
  print.mode = c("raw", "percent"),
  sigdigs = 3, # the amount of significant digits in percent
  # Customize appearance (optional)
  fill = c("#0072B2", "#0098ed", "#87CEEB"),
#  cat.col = c("#0072B2", "#0072B2", "#0072B2"),
  cex = 1.5, # Font size for counts
  cat.cex = 1.2, # Font size for category names
  cat.dist = c(0.04, 0.04, 0.04),
  # height = 2000,
  # width = 2000,
  cat.default.pos = "outer",
  cat.pos = c(-14, 14, 175), 
    cat.fontfamily = "sans",
    fontfamily = "sans",
  main = "Downregulated in\nPolyA Biased",
  main.fontfamily = "sans",
  main.cex = 1.3, # Font size for main title
  disable.logging = TRUE
)

ggsave(Fig_S16, file="../../Figures/Fig_S16.png", device = "png")

Fig_S16
```

### Fig S17

```{r Fig_S17}
Fig_S17 <- venn.diagram(
  x = down_riboDbiased_all,
  category.names = c(
    "SS to aRMS",
    "WT to NB",
    "AML to ALL"
    ),
  filename = NULL, # Save as a rds file
  output = TRUE,
  print.mode = c("raw", "percent"),
  sigdigs = 3, # the amount of significant digits in percent
  # Customize appearance (optional)
  fill = c("#E69F00", "#ff9b00", "#e6b200"),
#  cat.col = c("#E69F00", "#E69F00", "#E69F00"),
  cex = 1.5, # Font size for counts
  cat.cex = 1.2, # Font size for category names
  cat.dist = c(0.04, 0.04, 0.04), # distance of category name to VD
  # height = 2000,
  # width = 2000,
  cat.default.pos = "outer", # location of category names
  cat.pos = c(-14, 14, 175), # position of category names
  main = "Downregulated in \nRiboD Biased",
    fontfamily = "sans",
  main.fontfamily = "sans",
    cat.fontfamily = "sans",
  main.cex = 1.3, # Font size for main title
  disable.logging = TRUE
)

ggsave(Fig_S17, file="../../Figures/Fig_S17.png", device = "png")

Fig_S17
```

### Session Info

```{r}
sessioninfo::session_info()
```
