---
title: "THR13_0970_S12-S17_proportion"
Date: "`r Sys.Date()`"
format: 
  gfm:
    df-print: kable
editor: visual
---

## THR13_0970 matched PolyA / RiboD

Stacked bar chart showing the proportion of unique genes expressed at different log2(TPM+1) levels.

```{r load library}
library(tidyverse)
library(patchwork)
library(cowplot)
```

```{r load in expr file}
rsem_log2TPM1_THR13 <- read_tsv("../input_data/matched_THR13_0970/rsem_ensembl_log2TPM1_THR13_0970_S12-S17.tsv.gz")
```

```{r filter by sample}
THR13_0970_S12 <- rsem_log2TPM1_THR13 %>%
  filter(full_sample == "THR13_0970_S12")

THR13_0970_S13 <- rsem_log2TPM1_THR13 %>%
  filter(full_sample == "THR13_0970_S13")

THR13_0970_S14 <- rsem_log2TPM1_THR13 %>%
  filter(full_sample == "THR13_0970_S14")

THR13_0970_S15 <- rsem_log2TPM1_THR13 %>%
  filter(full_sample == "THR13_0970_S15")

THR13_0970_S16 <- rsem_log2TPM1_THR13 %>%
  filter(full_sample == "THR13_0970_S16")

THR13_0970_S17 <- rsem_log2TPM1_THR13 %>%
  filter(full_sample == "THR13_0970_S17")
```

Define log2(TPM+1) bins

```{r expr bins}
expr_bins <- c(0, 1e-10, 0.09, 0.99, 2.99, 4.99, Inf)

expr_labels <- c("0","0-0.09", "0.1-0.99", "1-2.99", "3-4.99", ">5")
```

define gene medians function

```{r gene medians function}
# compute_gene_medians <- function(df) {
#   df %>% 
#     rowwise() %>% 
#     mutate(median_expr = median(c_across(starts_with("T")), na.rm = TRUE)) %>%
#     ungroup() %>%
#     select(HugoID, median_expr, lib_prep, full_sample)
# }

```

Compute gene medians

```{r}
# THR13_0970_S12_med <- compute_gene_medians(THR13_0970_S12)
# # this is the same as original value, since the median of 1 sample is just that 1 sample's value
```

Bin genes into expression levels

```{r all_expr_bins}
all_expr_bins <- rsem_log2TPM1_THR13 %>%
  mutate(
    ExprBin = cut(
      log2TPM1,
      breaks = expr_bins,
      labels = expr_labels,
      include.lowest = TRUE
    )
  )
```

Compute proportion of genes in each bin per lib prep

```{r bin_prop}
bin_prop <- all_expr_bins %>% 
  group_by(full_sample, ExprBin) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(full_sample) %>%
  mutate(Proportion = n / sum(n))

bin_prop_libprep <- bin_prop %>%
  mutate(lib_prep = case_when(
    full_sample == "THR13_0970_S12" ~ "polyA",
    full_sample == "THR13_0970_S13" ~ "polyA",
    full_sample == "THR13_0970_S14" ~ "polyA",
    full_sample == "THR13_0970_S15" ~ "riboD",
    full_sample == "THR13_0970_S16" ~ "riboD",
    full_sample == "THR13_0970_S17" ~ "riboD"
  ))
```

Custom color theme

```{r theme_1C}
theme_1C <- function(base_size = 14) {
  theme_minimal(base_size = base_size) +
    theme(
      legend.position = "right",
      legend.title = element_blank(),
      panel.grid.major = element_line(color = "grey85", linewidth = 0.3),
      panel.grid.minor = element_blank(),
      axis.line = element_line(color = "black", linewidth = 0.4),
      axis.ticks = element_line(color = "black", linewidth = 0.4),
      strip.text = element_text(face = "bold", size = base_size * 0.9),
      plot.title = element_text(face = "bold", size = base_size * 1.1, hjust = 0.5),
      axis.title.y = element_text(angle = 90, hjust = 0.5, size = 16), 
      axis.title.x = element_text(angle = 0, hjust = 0.5, size = 17), 
      axis.text.x = element_text(angle = 0, hjust = 0.5, size = 14),
      plot.margin = margin(10, 10, 10, 10)
    )
}

scale_fill_compendia <- function() {
  scale_fill_manual(values = c(
    "polyA" = "#E69F00",  # yellow
    "riboD" = "#0072B2"   # blue
  ))
}
scale_color_compendia <- function() {
  scale_color_manual(values = c( 
    "polyA" = "#E69F00", 
    "riboD" = "#0072B2" ))
  }

```

Generate stacked bar plot

```{r prop_plot}
# Get unique THIDs
samplesC <- unique(bin_prop_libprep$full_sample)

# Generate one plot per sample
prop_plot <- map(samplesC, function(d) {
  
  dfC <- bin_prop_libprep %>% filter(full_sample == d)
  
  ggplot(dfC, aes(x = full_sample, y = Proportion, fill = ExprBin)) +
    geom_bar(stat = "identity", position = "stack") +
    scale_fill_viridis_d(
      option = "D", 
      name = expression(atop("Expression", "in log"[2]*"(TPM+1)"))
      ) +
    labs(
      # title = paste(d),
      x = NULL,
      y = "Proportion of Genes",
      fill = "Expression Level"
    ) +
    theme_1C() +
    facet_grid(~ lib_prep, scales = "free_x", space = "free_x")
})

# Name the plots by THIDs
names(prop_plot) <- samplesC
prop_plot
```

Plotting all together

```{r combined_prop_plot}
prop_plot_names <- names(prop_plot)
n <- length(prop_plot_names)
ncols <- 6
bottom_row <- prop_plot_names[seq(from = ceiling(n / ncols) * ncols - ncols + 1, to = n)]


plots_subset <- imap(prop_plot[prop_plot_names], function(p, name) {
  if (!name %in% bottom_row) {
    # hide x-axis on all panels except the last
    p + theme(
      axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      axis.ticks.x = element_blank()
    )
  } else {
    # show x-axis only on the last panel
    p + theme(
      axis.text.x = element_text(angle = 90, hjust = 1, size = 8),
      axis.title.x = element_text(size = 12)
    )
  }
})

combined_prop_plot <- wrap_plots(plots_subset, ncol = 6) +
  plot_layout(guides = "collect", axis_titles = "collect", axes = "collect") +
  plot_annotation(
    theme = theme(legend.position = "right")
  ) &
  theme(
    plot.margin = margin(t = 2, b = 2, l = 4, r = 4),
    plot.title = element_text(hjust = 0.35, face = "bold", size = 14),
    legend.title = element_text(size = 12)
  )

combined_prop_plot
```

Session Info

```{r sessioninfo}
sessioninfo::session_info()
```
