---
title: "THR13_0970_S12-S17_median_scatter"
Date: "`r Sys.Date()`"
format: 
  gfm:
    df-print: kable
editor: visual
---

## THR13_0970 matched PolyA / RiboD

Scatterplot showing the median expression level per gene between polyA and riboD

```{r load libraries}
library(tidyverse)
library(ggrepel)
library(patchwork)
```

```{r load in expr file}
rsem_log2TPM1_THR13 <- read_tsv("../input_data/matched_THR13_0970/rsem_ensembl_log2TPM1_THR13_0970_S12-S17.tsv.gz")
```

Compute gene medians

```{r polyA riboD}
# separating PolyA and RiboD
THR13_polyA <- rsem_log2TPM1_THR13 %>%
  filter(lib_prep == "polyA") %>%
  mutate(Disease = "DIPG4")

THR13_polyA_wide <- THR13_polyA %>%
  select(full_sample, ensembl_gene_ID, HugoID, log2TPM1) %>%
  pivot_wider(names_from = full_sample, values_from = log2TPM1)

THR13_riboD <- rsem_log2TPM1_THR13 %>%
  filter(lib_prep == "riboD") %>%
  mutate(Disease = "DIPG4")

THR13_riboD_wide <- THR13_riboD %>%
  select(full_sample, ensembl_gene_ID, HugoID, log2TPM1) %>%
  pivot_wider(names_from = full_sample, values_from = log2TPM1)
```

```{r polyA medians riboD medians}
# Find gene medians in polyA
THR13_polyA_medians <- THR13_polyA_wide %>%
  rowwise() %>%
  mutate(THR13_polyA_median = median(c_across(starts_with("T")), na.rm = TRUE)) %>%
  ungroup() %>%
  select(ensembl_gene_ID, HugoID, THR13_polyA_median)

# Find gene medians in riboD
THR13_riboD_medians <- THR13_riboD_wide %>%
  rowwise() %>%
  mutate(THR13_riboD_median = median(c_across(starts_with("T")), na.rm = TRUE)) %>%
  ungroup() %>%
  select(ensembl_gene_ID, HugoID, THR13_riboD_median)
```

```{r THR13_gene_medians}
# combine
THR13_gene_medians <- THR13_polyA_medians %>%
  inner_join(THR13_riboD_medians, by = "ensembl_gene_ID")
```

```{r plot_theme}
plot_theme <- function(base_size = 14) {
  theme_minimal(base_size = base_size) +
    theme(
      legend.position = "top",
      legend.title = element_blank(),
      panel.grid.major = element_line(color = "grey85", linewidth = 0.3),
      panel.grid.minor = element_blank(),
      axis.line = element_line(color = "black", linewidth = 0.4),
      axis.ticks = element_line(color = "black", linewidth = 0.4),
      strip.text = element_text(face = "bold", size = base_size * 0.9),
      plot.title = element_text(face = "bold", size = base_size * 1, hjust = 0.5),
      plot.margin = margin(10, 10, 10, 10)
    )
}

scale_fill_compendia <- function() {
  scale_fill_manual(values = c(
    "riboD" = "#E69F00",  # yellow
    "polyA" = "#0072B2"   # blue
  ))
}
scale_color_compendia <- function() {
  scale_color_manual(values = c( 
    "riboD" = "#E69F00", 
    "polyA" = "#0072B2" ))
  }
```

Compute residual for each gene

```{r THR13_gene_medians_res}
# for each gene in each disease, taking the average riboD expression and subtracting from the average polyA expression
THR13_gene_medians_res <- THR13_gene_medians %>%
  mutate(
    residual = THR13_riboD_median - THR13_polyA_median
  )
```

Label representative polyadenylated and non-polyadenylated gene

```{r THR13_gene_medians_res format}
# representative polyadenylated genes were found in THR13_0970_S12-S17/THR13_0970_S12-S17_rep_genes.md, calculated as the median expression level in PolyA samples divided by the median expression level in RiboD samples

THR13_gene_medians_res <- THR13_gene_medians_res %>%
  mutate(
    label_color = case_when(
    ensembl_gene_ID == "ENSG00000165609.12" ~ "#BB5566", #NUDT5
    ensembl_gene_ID == "ENSG00000184357.4" ~ "#BB5566", #HIST1H1B
    TRUE ~ "grey70"
    )
  ) %>%
  mutate(
    label = case_when(
      ensembl_gene_ID == "ENSG00000165609.12" ~ HugoID.x,
      ensembl_gene_ID == "ENSG00000184357.4" ~ HugoID.x, # HIST1H1B + median ratio gene
      TRUE ~ NA_character_
    )
  )
```

Plot average expression across library prep methods

```{r med_scatterplot}
med_scatterplot <- ggplot(THR13_gene_medians_res, aes(x = THR13_polyA_median, y = THR13_riboD_median)) +
  geom_point(data = THR13_gene_medians_res %>% filter(is.na(label)),
             color = "grey70", alpha = 0.5, size = 1.2) +
  geom_point(data = THR13_gene_medians_res %>% filter(!is.na(label)),
             aes(color = label_color),
             size = 2.5, alpha = 0.9) +
  geom_text_repel(
    aes(label = label),
    size = 4.5,
    max.overlaps = Inf,
    min.segment.length = 0,
    box.padding = 0.4,
    point.padding = 0.2
  ) +
  scale_color_identity() +   # use colors exactly as defined
  geom_abline(slope = 1, intercept = 0,
                linetype = "dashed", color = "gray50") +
  labs(title = "matched DIPGIV") +
    xlab(bquote(Median~PolyA~log[2](TPM+1))) +
    ylab(bquote(Median~RiboD~log[2](TPM+1))) +
    theme_minimal(base_size = 14) +
    plot_theme()
med_scatterplot
```

Session Info

```{r SessionInfo}
sessioninfo::session_info()
```
