---
title: "THR13_0970_S12-S17_correlogram"
Date: "`r Sys.Date()`"
format: 
  gfm:
    df-print: kable
editor: visual
---

## THR13_0970 matched PolyA / RiboD

Correlogram showing similarity between datasets

```{r load library}
library(tidyverse)
library(corrr)
library(GGally)
library(corrplot)
```

```{r load in expr file}
rsem_log2TPM1_THR13 <- read_tsv("../input_data/matched_THR13_0970/rsem_ensembl_log2TPM1_THR13_0970_S12-S17.tsv.gz")
```

```{r wide}
# pivot to wide format
rsem_wide <- rsem_log2TPM1_THR13 %>%
  select(full_sample, ensembl_gene_ID, log2TPM1) %>%
  pivot_wider(names_from = full_sample, values_from = log2TPM1)
```

```{r corrr}
# convert to matrix
rsem_matrix <- rsem_wide %>%
  column_to_rownames("ensembl_gene_ID") %>%
  as.matrix()

set.seed(123) # for reproducibility
# Compute Spearman correlation 
rsem_correlation <- cor(rsem_matrix, method = "spearman", use = "pairwise.complete.obs") #pairwise.complete.obs = the correlation between each pair of variables is computed using all complete pairs of those particular variables
# ^ I think this means NAs will not be counted in calculation
```

```{r prep_map}
prep_map <- c(
  "THR13_0970_S12" = "PolyA",
  "THR13_0970_S13" = "PolyA",
  "THR13_0970_S14" = "PolyA",
  "THR13_0970_S15" = "RiboD",
  "THR13_0970_S16" = "RiboD",
  "THR13_0970_S17" = "RiboD"
)

# Rename columns to include prep method, e.g. "S12 (PolyA)"
colnames(rsem_matrix) <- paste0(
  colnames(rsem_matrix),
  " (", prep_map[colnames(rsem_matrix)], ")"
)
```

```{r cor_color_fn}
# integrate density plot with coefficient value and color by coefficient value

cor_color_fn <- function(data, mapping, ...) {
  corr <- eval_data_col(data, mapping$x) %>%
    cor(eval_data_col(data, mapping$y), method = "spearman", use = "pairwise.complete.obs")
  
  ggally_cor(data, mapping, method = "spearman") +
    theme_bw() +
    theme(panel.background = element_rect(
      fill = scales::col_numeric(c("#ec944d", "white", "#084c8b"), c(0.8,1))(corr)
    ),
    panel.grid = element_blank())
}
```

```{r rsem_ggpairs_plot}
rsem_ggpairs_plot <- ggpairs(
  rsem_matrix,
  # upper = list(continuous = wrap(cor_color_fn, method = "spearman")),
  lower = list(continuous = "blank"),
  upper = list(continuous = wrap(cor_color_fn, method = "spearman")),
  diag = list(continuous = wrap("densityDiag"))
  # diag = list(continuous = "blank")
) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(
    strip.text.y = element_text(angle = 0, size = 9),
    strip.text.x = element_text(angle = 45, size = 9)
  ) +
  theme(panel.grid = element_blank())
rsem_ggpairs_plot
```

```{r}
ggsave(
  "rsem_ggpairs_plot.png",
  rsem_ggpairs_plot,
  width = 10, height = 12, units = "in", dpi = 300
)
```

```{r}
# with scatterplot
rsem_ggpairs_plot_scatter <- ggpairs(
  rsem_matrix,
  lower = list(continuous = wrap("points", alpha = 0.3, size = 0.5)),
  upper = list(continuous = wrap(cor_color_fn, method = "spearman")),
  diag = list(continuous = wrap("densityDiag"))
  # diag = list(continuous = "blank")
) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(
    strip.text.y = element_text(angle = 0, size = 9),
    strip.text.x = element_text(angle = 45, size = 9)
  ) +
  theme(panel.grid = element_blank())
rsem_ggpairs_plot_scatter
```

```{r}
ggsave(
  "rsem_ggpairs_plot_scatter.png",
  rsem_ggpairs_plot_scatter,
  width = 10, height = 12, units = "in", dpi = 300
)
```

Session Info

```{r}
sessioninfo::session_info()
```
